name: suns
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.8
  - pip=19.3.1=py37_0
  - numpy
  - h5py
  - keras
  - matplotlib
  - numba
  - opencv
  - scikit-image
  - scikit-learn
  - scipy
  - shapely 
  # - tensorflow==1.15
  - tensorflow-gpu==1.15
  - pip:
    - fissa==0.6.1
    - pyfftw
    - tensorflow-estimator==1.15.1
